### ISSUE TITLE
Investigate Aggregate Healthcheck instability

### ISSUE THREAD

**Issue by efinlay24** [Financial-Times/upp-aggregate-healthcheck#23]
It mostly happens when lots of applications are not healthy, like after a cluster update using the provisioner.

This is the stacktrace that I see:

```
goroutine 14523 [running]:
net/http.(*conn).serve.func1(0xc420f6de80)
	/usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0x1271180, 0xc42021d190)
	/usr/local/go/src/runtime/panic.go:458 +0x243
main.buildHealthcheckJSONResponse(0x1c46000, 0xc420b0cea0, 0x3ff0000000000000, 0x0, 0x0, 0xc421477590, 0x26, 0x148005b, 0x2e, 0xc420e3e000, ...)
	/go/src/upp-aggregate-healthcheck/handler.go:322 +0x1c8
main.(*httpHandler).handleServicesHealthCheck(0xc420384b40, 0x1c46000, 0xc420b0cea0, 0xc420a7cc30)
	/go/src/upp-aggregate-healthcheck/handler.go:196 +0x5d0
main.(*httpHandler).(main.handleServicesHealthCheck)-fm(0x1c46000, 0xc420b0cea0, 0xc420a7cc30)
	/go/src/upp-aggregate-healthcheck/main.go:82 +0x48
net/http.HandlerFunc.ServeHTTP(0xc420438870, 0x1c46000, 0xc420b0cea0, 0xc420a7cc30)
	/usr/local/go/src/net/http/server.go:1726 +0x44
upp-aggregate-healthcheck/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420407a90, 0x1c46000, 0xc420b0cea0, 0xc420a7cc30)
	/go/src/upp-aggregate-healthcheck/vendor/github.com/gorilla/mux/mux.go:114 +0x10d
net/http.serverHandler.ServeHTTP(0xc4202fd600, 0x1c46000, 0xc420b0cea0, 0xc420a7ca50)
	/usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc420f6de80, 0x1c4c940, 0xc4219eea00)
	/usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d
```

https://trello.com/c/0ll88wY5/126-aggregate-healthcheck-becomes-unstable-sometimes

**Comment by carlosroman** [comment]
Issue has been archived.
